birds = [
    "Alpine Accentor",
    "Alpine Chough",
    "Alpine Swift",
    "Arctic Tern",
    "Avocet",
    "Barn Owl",
    "Barn Swallow",
    "Barred Warbler",
    "Bearded Reedling",
    "Bee-eater",
    "Bittern",
    "Black Grouse",
    "Black Kite",
    "Black Redstart",
    "Black Stork",
    "Black Tern",
    "Blackbird",
    "Blackcap",
    "Black-headed Gull",
    "Black-necked Grebe",
    "Blue Rock Thrush",
    "Blue Tit",
    "Bluethroat",
    "Booted Eagle",
    "Brambling",
    "Bullfinch",
    "Buzzard",
    "Cattle Egret",
    "Chaffinch",
    "Chiffchaff",
    "Chough",
    "Cirl Bunting",
    "Coal Tit",
    "Collared Dove",
    "Common Crane",
    "Common Cuckoo",
    "Common Gull",
    "Common Kingfisher",
    "Common Merganser",
    "Common Moorhen",
    "Common Nightingale",
    "Common Pochard",
    "Common Redpoll",
    "Common Redshank",
    "Common Sandpiper",
    "Common Scoter",
    "Common Shelduck",
    "Common Snipe",
    "Common Starling",
    "Common Swift",
    "Common Tern",
    "Common Whitethroat",
    "Common Wood Pigeon",
    "Corn Bunting",
    "Corn Crake",
    "Crested Lark",
    "Crested Tit",
    "Crossbill",
    "Cuckoo",
    "Curlew",
    "Dartford Warbler",
    "Dipper",
    "Dotterel",
    "Dunnock",
    "Eagle Owl",
    "Egyptian Vulture",
    "Eider",
    "Fieldfare",
    "Firecrest",
    "Fulmar",
    "Gadwall",
    "Gannet",
    "Garden Warbler",
    "Garganey",
    "Glossy Ibis",
    "Goldcrest",
    "Golden Eagle",
    "Golden Oriole",
    "Golden Plover",
    "Goldfinch",
    "Goosander",
    "Goshawk",
    "Grasshopper Warbler",
    "Great Black-backed Gull",
    "Great Crested Grebe",
    "Great Grey Shrike",
    "Great Spotted Cuckoo",
    "Great Spotted Woodpecker",
    "Great Tit",
    "Great White Egret",
    "Greater Flamingo",
    "Greater Spotted Eagle",
    "Green Sandpiper",
    "Green Woodpecker",
    "Greenfinch",
    "Greenshank",
    "Grey Heron",
    "Grey Partridge",
    "Grey Plover",
    "Grey Wagtail",
    "Grey-headed Woodpecker",
    "Greylag Goose",
    "Griffon Vulture",
    "Guillemot",
    "Hawfinch",
    "Hen Harrier",
    "Herring Gull",
    "Hobby",
    "Hoopoe",
    "House Martin",
    "House Sparrow",
    "Iberian Green Woodpecker",
    "Iberian Magpie",
    "Iberian Shrike",
    "Iberian Warbler",
    "Jack Snipe",
    "Jackdaw",
    "Jay",
    "Kentish Plover",
    "Kestrel",
    "Kingfisher",
    "Lapwing",
    "Lesser Black-backed Gull",
    "Lesser Kestrel",
    "Lesser Spotted Eagle",
    "Lesser Spotted Woodpecker",
    "Linnet",
    "Little Bittern",
    "Little Bustard",
    "Little Egret",
    "Little Grebe",
    "Little Owl",
    "Little Ringed Plover",
    "Little Tern",
    "Long-eared Owl",
    "Long-tailed Tit",
    "Magpie",
    "Mallard",
    "Marsh Harrier",
    "Marsh Tit",
    "Meadow Pipit",
    "Mediterranean Gull",
    "Merlin",
    "Mistle Thrush",
    "Montagu's Harrier",
    "Mute Swan",
    "Nightjar",
    "Nuthatch",
    "Osprey",
    "Oystercatcher",
    "Pallid Harrier",
    "Penduline Tit",
    "Peregrine Falcon",
    "Pied Flycatcher",
    "Pied Wagtail",
    "Pine Grosbeak",
    "Pintail",
    "Purple Heron",
    "Purple Sandpiper",
    "Purple Swamphen",
    "Pygmy Owl",
    "Quail",
    "Raven",
    "Red Kite",
    "Red-backed Shrike",
    "Red-breasted Flycatcher",
    "Red-breasted Merganser",
    "Red-crested Pochard",
    "Red-footed Falcon",
    "Red-legged Partridge",
    "Red-throated Diver",
    "Redstart",
    "Reed Bunting",
    "Reed Warbler",
    "Ring Ouzel",
    "Ring-necked Pheasant",
    "Robin",
    "Rock Bunting",
    "Rock Dove",
    "Rock Pipit",
    "Rook",
    "Roseate Tern",
    "Ruff",
    "Sand Martin",
    "Savi's Warbler",
    "Scops Owl",
    "Serin",
    "Shag",
    "Short-eared Owl",
    "Short-toed Eagle",
    "Siskin",
    "Skylark",
    "Slavonian Grebe",
    "Smew",
    "Snow Bunting",
    "Song Thrush",
    "Sparrowhawk",
    "Spoonbill",
    "Spotted Crake",
    "Spotted Flycatcher",
    "Spotted Redshank",
    "Stone Curlew",
    "Stonechat",
    "Storm Petrel",
    "Tawny Owl",
    "Temminck's Stint",
    "Tree Pipit",
    "Tree Sparrow",
    "Treecreeper",
    "Tufted Duck",
    "Turtle Dove",
    "Twite",
    "Wallcreeper",
    "Water Pipit",
    "Water Rail",
    "Waxwing",
    "Wheatear",
    "Whinchat",
    "White Stork",
    "White Wagtail",
    "White-backed Woodpecker",
    "White-tailed Eagle",
    "Willow Tit",
    "Willow Warbler",
    "Wood Sandpiper",
    "Wood Warbler",
    "Woodcock",
    "Woodlark",
    "Wren",
    "Wryneck",
    "Yellow Wagtail",
    "Yellowhammer"
]

target = input("BIRD? :J\n")

low = 0
high = len(birds) - 1
checks = 0

while low < high:
    middle = (low + high) // 2
    checks=checks+1

    if birds[middle] == target:
        print("DONE")
        low = high
    elif birds[middle] < target:
        low = middle + 1
    else:
        high = middle - 1